/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Q7Jlf7RMau1
 */
import { CardContent, CardFooter, Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { CarouselItem, CarouselContent, CarouselPrevious, CarouselNext, Carousel } from "@/components/ui/carousel"

export function Slider() {
  return (
    <Carousel className="w-full max-w-xs">
      <CarouselContent>
        <CarouselItem>
          <div className="p-1">
            <Card>
              <img
                alt="Profile Image"
                className="object-cover w-full p-5 rounded-[2.5rem]"
                height={200}
                src="public\asset\Images\engine.png"
                style={{
                  aspectRatio: "200/200",
                  objectFit: "cover",
                }}
                width={200}
              />
              <CardContent className="text-center">
                <p className="text-lg font-semibold">Enginering</p>
                <p className="text-sm text-gray-500 dark:text-gray-400">Engineering courses offer comprehensive training in design, analysis, and problem-solving for aspiring engineers.</p>
              </CardContent>
              <CardFooter className="flex justify-center">
                <Button className="bg-black rounded-full py-2 px-8 text-white">Check</Button>
              </CardFooter>
            </Card>
          </div>
        </CarouselItem>
        <CarouselItem>
          <div className="p-1">
            <Card>
              <img
                alt="Profile Image"
                className="object-cover w-full p-5 rounded-[2.5rem]"
                height={200}
                src="public\asset\Images\lawyer.png"
                style={{
                  aspectRatio: "200/200",
                  objectFit: "cover",
                }}
                width={200}
              />
              <CardContent className="text-center">
                <p className="text-lg font-semibold">Lawyer</p>
                <p className="text-sm text-gray-500 dark:text-gray-400">Lawyer courses equip students with legal expertise, critical thinking, and advocacy skills essential for legal practice."</p>
              </CardContent>
              <CardFooter className="flex justify-center">
                <Button>Go To Profile</Button>
              </CardFooter>
            </Card>
          </div>
        </CarouselItem>
        <CarouselItem>
          <div className="p-1">
            <Card>
              <img
                alt="Profile Image"
                className="object-cover w-full p-5 rounded-[2.5rem]"
                height={200}
                src="public\asset\Images\cinema.png"
                style={{
                  aspectRatio: "200/200",
                  objectFit: "cover",
                }}
                width={200}
              />
              <CardContent className="text-center">
                <p className="text-lg font-semibold">Acting</p>
                <p className="text-sm text-gray-500 dark:text-gray-400">"Acting courses immerse students in the art of performance, honing skills in expression, characterization, and stage presence."</p>
              </CardContent>
              <CardFooter className="flex justify-center">
                <Button>Go To Profile</Button>
              </CardFooter>
            </Card>
          </div>
        </CarouselItem>
      </CarouselContent>
      <CarouselPrevious />
      <CarouselNext />
    </Carousel>
  )
}
