/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/0TROjrAmWWA
 */

import { Link } from "react-router-dom"

export function Footer() {
  return (
    <div className="border-t-[1px] w-full">
    <footer className="w-full py-6 md:py-12  ">
      <div className="container flex flex-col items-center gap-4 px-4 md:px-6">
        <div className="grid gap-1 text-center">
          <Link className="inline-flex font-bold text-2xl hover:text-blue-500" to="#">
            Company
          </Link>
          <p className="text-sm text-gray-500 dark:text-gray-400">
            A description of the company or the website. This can be a brief tagline or a description of the services
            offered. It helps users understand the purpose of the website at a glance.
          </p>
        </div>
        <nav className="grid grid-cols-2 gap-8 min-[400px]:grid-cols-4">
          <div className="space-y-2">
            <h2 className="text-lg font-semibold">Product</h2>
            <ul className="space-y-1.5">
              <li>
                <Link className="hover:text-blue-500" to="#">
                  Features
                </Link>
              </li>
              <li>
                <Link className="hover:text-blue-500" to="#">
                  Integrations
                </Link>
              </li>
              <li>
                <Link className="hover:text-blue-500" to="#">
                  Pricing
                </Link>
              </li>
            </ul>
          </div>
          <div className="space-y-2">
            <h2 className="text-lg font-semibold">Company</h2>
            <ul className="space-y-1.5">
              <li>
                <Link className="hover:text-blue-500" to="#">
                  About
                </Link>
              </li>
              <li>
                <Link className="hover:text-blue-500" to="#">
                  Customers
                </Link>
              </li>
              <li>
                <Link className="hover:text-blue-500" to="#">
                  Careers
                </Link>
              </li>
            </ul>
          </div>
          <div className="space-y-2">
            <h2 className="text-lg font-semibold">Resources</h2>
            <ul className="space-y-1.5">
              <li>
                <Link className="hover:text-blue-500" to="#">
                  Support
                </Link>
              </li>
              <li>
                <Link className="hover:text-blue-500" to="#">
                  Documentation
                </Link>
              </li>
              <li>
                <Link className="hover:text-blue-500" to="#">
                  Community
                </Link>
              </li>
            </ul>
          </div>
          <div className="space-y-2">
            <h2 className="text-lg font-semibold">Connect</h2>
            <ul className="space-y-1.5">
              <li>
                <Link className="hover:text-blue-500" to="#">
                  Contact Us
                </Link>
              </li>
              <li>
                <Link className="hover:text-blue-500" to="#">
                  Webinars
                </Link>
              </li>
              <li>
                <Link className="hover:text-blue-500" to="#">
                  Events
                </Link>
              </li>
            </ul>
          </div>
        </nav>
        <div className="flex items-center justify-center gap-4 min-[400px]:justify-between flex-col md:flex-row">
          <div className="flex items-center gap-4 text-sm">
            <span>© 2023 Company</span>
            <span>Privacy Policy</span>
            <span>Terms of Service</span>
          </div>
          <div className="flex items-center gap-4 text-sm">
            <Link className="text-gray-500 hover:text-gray-900 dark:hover:text-gray-50" to="#">
              <TwitterIcon className="w-4 h-4" />
              <span className="sr-only">Twitter</span>
            </Link>
            <Link className="text-gray-500 hover:text-gray-900 dark:hover:text-gray-50" to="#">
              <FacebookIcon className="w-4 h-4" />
              <span className="sr-only">Facebook</span>
            </Link>
            <Link className="text-gray-500 hover:text-gray-900 dark:hover:text-gray-50" to="#">
              <InstagramIcon className="w-4 h-4" />
              <span className="sr-only">Instagram</span>
            </Link>
          </div>
        </div>
      </div>
    </footer>
    </div>
  )
}


function TwitterIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>
  )
}


function FacebookIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z" />
    </svg>
  )
}


function InstagramIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="20" x="2" y="2" rx="5" ry="5" />
      <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z" />
      <line x1="17.5" x2="17.51" y1="6.5" y2="6.5" />
    </svg>
  )
}
